apiVersion: v1
kind: Pod
metadata:
  name: emptydir
  namespace: webinar
spec:
  containers:
  - image: busybox
    command: ['sh', '-c', 'while true; do date >> /etc/time_log.txt; sleep 2; done']
    imagePullPolicy: IfNotPresent
    name: busybox-1
    volumeMounts:
    - mountPath: /etc
      name: my-volume
  - image: busybox
    command: ['sh', '-c', 'while true; do tail /etc/time_log.txt; sleep 2; done']
    imagePullPolicy: IfNotPresent
    name: busybox-2
    volumeMounts:
    - mountPath: /etc
      name: my-volume
  volumes:
  - name: my-volume
    emptyDir: {}
