apiVersion: v1
kind: Pod
metadata:
  name: pod-with-configmap
  namespace: webinar
spec:
  containers:
  - image: busybox
    command: ['sh', '-c', 'while true; do cat /test-configmap/application.properties; sleep 3600; done']
    imagePullPolicy: IfNotPresent
    name: busybox-1
    volumeMounts:
    - mountPath: /test-configmap
      name: my-volume
  volumes:
  - name: my-volume
    configMap:
      name: "application-config"
