apiVersion: v1
kind: Pod
metadata:
  name: productservice-pod
  labels:
    app: productservice
spec:
  containers:
  - name: nginx-container
    image: nginx
    livenessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 15
