apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: ubuntu-container
    image: phusion/baseimage
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ['sh', '-c', 'echo Hello DevOps Underground Fellows > /pod-data/index.html && sleep 3600']
